-- Migración de costos desde costos 2026.xlsx — ejecutar UNA vez tras schema_fase4.sql
begin;
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('hoddies', 'topper', 6.18, 1.5, 2.3, 0.14, 0, 0.2, 40.65, 35, 25, 22, 19.36, '{"HODDIE"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('hoddie basica', 'topper', 6.18, 1.5, 0, 0.14, 0, 0.2, 32.95, 28, 18, 15.84, 13.5, '{"HODDIE","COLOR ENTERO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('camiseta', 'cotone', 5.34, 0.8, 2.3, 0.24, 0, 0.2, 31.85, 25, 22, 19.36, 17.0368, '{"CAMISETA"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('camiseta basica', 'cotone', 5.34, 0.8, 0, 0.24, 0, 0.2, 22.2, 20, 15, 13.2, 11.616, '{"CAMISETA","COLOR ENTERO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('cuello chino', 'dornella', 5.38, 1.5, 0, 0.24, 0.1, 0.2, 21.95, 23, 19, 16.72, 14.7136, '{"CUELLO CHINO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('buzo cuello chino', 'daimond', 5.16, 1.5, 0, 0.24, 0.1, 0.2, 31.52, 28, 21, 18.48, 16.2624, '{"BUZO","CUELLO CHINO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('pant mujer', 'nayara', 6.71, 1.25, 0, 0.24, 0.2, 0.2, 28.95, 28, 20, 17.6, 15.488, '{"PANT"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('polo mujer', 'jane soft', 1.56, 1.25, 0, 0.24, 0, 0.2, 16.65, 18, 14.5, 12.76, 11.2288, '{"POLO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('conjunto pantalon', 'nayara', 8.86, 1, 0, 0.24, 0.2, 0.2, 38.95, null, null, null, null, '{"CONJUNTO"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('bluza', 'nayara', 10.86, 1.5, 0, 0.24, 0.2, 0.2, 35.95, null, null, null, null, '{"BLUSA"}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('BLUZA (HANDEL)', 'HANDEL', 5.4, 1, 0, 0.24, 0.2, 0.2, 30, null, null, null, null, '{}');
insert into costos_prendas (producto, nombre_tela, costo_tela, maquila, dtf, corte, insumos, etiqueta, pvp_vatex, precio_online, precio_mayoreo_1_2, precio_mayoreo_3_5, precio_mayoreo_6plus, match_keywords) values ('PANTALON', 'HANDEL', 5.4, 1.5, 0, 0.24, 0.2, 0.2, 25, null, null, null, null, '{}');
commit;
